### ISSUE TITLE
关于部署使用（Gitalk报错与白屏）

### ISSUE THREAD

**Issue by Mieluoxxx** [EvanLuo42/oliver#1]
你好👋，我很喜欢你的作品，她足够的简洁优雅，非常符合我的审美。然而我似乎在部署上发生了一些问题，首先我配置了Gitalk但仍然报错，而且登录之后也会有白屏现象，希望您能抽空为我解答一下，万分感谢
```
TypeError: /Users/moguw/Downloads/Hexo/themes/Oliver/layout/post.ejs:26
    24|     <script>
    25|         const gitalk = new Gitalk({
 >> 26|           clientID: '<%- theme.gitalk.client_id %>',
    27|           clientSecret: '<%- theme.gitalk.client_secret %>',
    28|           repo: '<%- theme.gitalk.repo %>',
    29|           owner: '<%- theme.gitalk.owner %>',

Cannot read properties of undefined (reading 'client_id')
    at eval ("/Users/moguw/Downloads/Hexo/themes/Oliver/layout/post.ejs":49:30)
    at post (/Users/moguw/Downloads/Hexo/node_modules/ejs/lib/ejs.js:703:17)
    at _View._compiled (/Users/moguw/Downloads/Hexo/node_modules/hexo/lib/theme/view.js:136:50)
    at _View.render (/Users/moguw/Downloads/Hexo/node_modules/hexo/lib/theme/view.js:39:17)
    at /Users/moguw/Downloads/Hexo/node_modules/hexo/lib/hexo/index.js:64:21
    at tryCatcher (/Users/moguw/Downloads/Hexo/node_modules/bluebird/js/release/util.js:16:23)
    at /Users/moguw/Downloads/Hexo/node_modules/bluebird/js/release/method.js:15:34
    at RouteStream._read (/Users/moguw/Downloads/Hexo/node_modules/hexo/lib/hexo/router.js:47:5)
    at Readable.read (node:internal/streams/readable:515:12)
    at resume_ (node:internal/streams/readable:1016:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
   ```
   
[![piptRun.png](https://z1.ax1x.com/2023/10/13/piptRun.png)](https://imgse.com/i/piptRun)

**Comment by EvanLuo42** [comment]
白屏似乎是因为我用的 API 在 Chrome 有点 bug，我之后重写一下暗色模式。如果不使用暗色模式应该是可以正常显示的。我用的色反 API，可能 Chrome 里面还是实验性 API。

**Comment by EvanLuo42** [comment]
那个报错应该是因为你需要在主题配置文件里面配置一下 Gitalk。
```
    24|     <script>
    25|         const gitalk = new Gitalk({
 >> 26|           clientID: '<%- theme.gitalk.client_id %>',
    27|           clientSecret: '<%- theme.gitalk.client_secret %>',
    28|           repo: '<%- theme.gitalk.repo %>',
    29|           owner: '<%- theme.gitalk.owner %>',
```
你可以按照这个上面的字段填一下你自己的。

如果你的配置文件还是叫 `_config_template.yml` 的话，你需要把 `_template` 删掉。

**Comment by EvanLuo42** [comment]
因为本来没想着公开只是自用所以没怎么完善 README，抱歉（
